"""Add anfangsseite and endseite to dokumente table

Revision ID: b6573425bc32
Revises: 993f035698da
Create Date: 2025-07-03 13:49:33.526534

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6573425bc32"
down_revision = "993f035698da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dokumente", schema=None) as batch_op:
        batch_op.add_column(sa.Column("anfangsseite", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("endseite", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dokumente", schema=None) as batch_op:
        batch_op.drop_column("endseite")
        batch_op.drop_column("anfangsseite")

    # ### end Alembic commands ###
