"""Initial migration

Revision ID: 6b78113d573d
Revises: 
Create Date: 2025-07-02 12:46:28.213333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b78113d573d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumente', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('dokumente_fundstelle_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'fundstellen', ['fundstelle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dokumente_fundstelle_id_fkey'), 'fundstellen', ['fundstelle_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
