"""Change anfangsseite and endseite to Integer

Revision ID: 993f035698da
Revises: 6b78113d573d
Create Date: 2025-07-02 12:48:31.771212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993f035698da'
down_revision = '6b78113d573d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundstellen', schema=None) as batch_op:
        batch_op.alter_column('anfangsseite',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='CASE WHEN anfangsseite ~ \'^[0-9]+$\' THEN anfangsseite::integer ELSE NULL END')
        batch_op.alter_column('endseite',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='CASE WHEN endseite ~ \'^[0-9]+$\' THEN endseite::integer ELSE NULL END')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundstellen', schema=None) as batch_op:
        batch_op.alter_column('endseite',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('anfangsseite',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
