# GitHub Actions Workflow for running daily updates via the updater module
name: Daily Update
on:
  schedule:
    - cron: '0 22 * * *'  # Runs at midnight German time daily
  workflow_dispatch:  

jobs:
  update:
    runs-on: ubuntu-latest 
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      # Install and generate German locale
      - name: Set up German locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8
          echo "LANG=de_DE.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=de_DE.UTF-8" >> $GITHUB_ENV

      # Cache python packages and model data
      - name: Cache python packages model data
        uses: actions/cache@v3
        with:
          path: |
            /opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/
            ~/.cache/huggingface
            ~/.cache/torch
            ~/.cache/docling
            ~/.cache/pip
          key: ${{ runner.os }}-models-${{ hashFiles('requirements.txt') }}-${{ hashFiles('.github/workflows/daily_update.yml') }}
          restore-keys: |
            ${{ runner.os }}-models-

      # Install dependencies (requirements.txt + those only needed for daily_update)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install gnews==0.4.0
          python -m pip install googlenewsdecoder==0.1.7
          python -m pip install docling==2.28.0
          python -m pip install pypdfium2==4.30.1

      # Launch script
      - name: Run daily update
        run: python -m gesetzgebung.updater.launch
        env:
          ES_HOST: ${{ secrets.ES_HOST }}
          ES_LAWS_INDEX: ${{ secrets.ES_LAWS_INDEX }}
          DATABASE_URL: ${{ secrets.SUPABASE_TRANSACTION_POOLER_URL }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ERROR_MAIL_PASSWORD: ${{ secrets.ERROR_MAIL_PASSWORD }}
          ERROR_MAIL_ADDRESS: ${{ secrets.ERROR_MAIL_ADDRESS }}
          DEVELOPER_MAIL_ADDRESS: ${{ secrets.DEVELOPER_MAIL_ADDRESS }}
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
