# GitHub Actions Workflow for running daily_update.py 
name: Daily Update
on:
  schedule:
    - cron: '0 22 * * *'  # Runs at midnight German time daily
  workflow_dispatch:  

jobs:
  update:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install gnews==0.4.0
          python -m pip install googlenewsdecoder==0.1.7
          python -m pip install docling==2.28.0
          python -m pip install pypdfium2==4.30.1
      
      - name: Run daily update
        run: python -m gesetzgebung.daily_update
        env:
          ES_HOST: ${{ secrets.ES_HOST }}
          ES_LAWS_INDEX: ${{ secrets.ES_LAWS_INDEX }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ERROR_MAIL_PASSWORD: ${{ secrets.ERROR_MAIL_PASSWORD }}
          ERROR_MAIL_ADDRESS: ${{ secrets.ERROR_MAIL_ADDRESS }}
          DEVELOPER_MAIL_ADDRESS: ${{ secrets.DEVELOPER_MAIL_ADDRESS }}
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
